WITH BOOKS AS (
    SELECT BK.BOOK_ID, BK.CATEGORY, AR.AUTHOR_NAME, BK.PRICE, BK.PUBLISHED_DATE, AR.AUTHOR_ID
    FROM BOOK BK
    JOIN AUTHOR AR
    ON BK.AUTHOR_ID = AR.AUTHOR_ID
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOKS BKS
JOIN (
    SELECT * FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'  
) AS BS
ON BKS.BOOK_ID = BS.BOOK_ID
GROUP BY AUTHOR_ID, BKS.CATEGORY
ORDER BY AUTHOR_ID, BKS.CATEGORY DESC;