SELECT AR.AUTHOR_ID, AR.AUTHOR_NAME, BK.CATEGORY,
SUM(BS.SALES * BK.PRICE) AS TOTAL_SALES
FROM BOOK BK
JOIN AUTHOR AR
ON BK.AUTHOR_ID = AR.AUTHOR_ID
JOIN(SELECT * FROM BOOK_SALES
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01')
AS BS
ON BK.BOOK_ID = BS.BOOK_ID
GROUP BY AR.AUTHOR_ID, BK.CATEGORY
ORDER BY AR.AUTHOR_ID, BK.CATEGORY DESC;