SELECT YG.CART_ID
FROM (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
) AS YG
LEFT JOIN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
) MK
ON YG.CART_ID = MK.CART_ID
WHERE MK.CART_ID IS NOT NULL
GROUP BY YG.CART_ID;

# "yogurt찾고, milk찾고 "