-- 코드를 입력하세요
# SELECT a1.USER_ID, a1.PRODUCT_ID 
# FROM ONLINE_SALE a1, ONLINE_SALE a2
# WHERE a1.USER_ID = a2.USER_ID AND a1.PRODUCT_ID = a2.PRODUCT_ID
# ORDER BY a1.USER_ID, a1.PRODUCT_ID DESC;

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;
