WITH SELL_DATA AS (
    SELECT ONLINE_SALE_ID, OS.USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE,
    YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
    OS.USER_ID AS TOTAL
    FROM ONLINE_SALE OS
    JOIN USER_INFO UI
    ON OS.USER_ID = UI.USER_ID
    WHERE YEAR(UI.JOINED) = '2021'
    GROUP BY OS.USER_ID, YEAR, MONTH
    ORDER BY OS.USER_ID
),
TOTAL AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT YEAR, MONTH, COUNT(USER_ID) AS PURCHASED_USERS,
ROUND((COUNT(USER_ID) / TOTAL.CNT), 1)AS PUCHASED_RATIO
FROM SELL_DATA, TOTAL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

#2021 가입, 상품구매 회원 수, 상품을 구매한 사람의 비율, 년 월 별로 출력