SELECT FD.PRODUCT_ID, FD.PRODUCT_NAME, (FD.PRICE * SUM(FO.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT FD
JOIN FOOD_ORDER FO
ON FD.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FD.PRODUCT_ID;
