WITH TYPE AS (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN TYPE TP
ON FH.FLAVOR = TP.FLAVOR
ORDER BY (TOTAL_ORDER + TP.TOTAL) DESC
LIMIT 3;