SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS JY
ON FH.FLAVOR = JY.FLAVOR
ORDER BY FH.TOTAL_ORDER + JY.TOTAL_ORDER DESC
LIMIT 3;