SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, DT.MCDP_CD, DT.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
LEFT JOIN PATIENT PT
ON AP.PT_NO = PT.PT_NO
LEFT JOIN DOCTOR DT
ON AP.MDDR_ID = DT.DR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
AND AP.APNT_CNCL_YN = 'N'
AND DT.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD;