WITH FE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS DEV
JOIN FE
ON DEV.SKILL_CODE & FE.CODE = FE.CODE
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;