WITH YEAR_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT HE.EMP_NO, HE.EMP_NAME,
CASE 
WHEN YG.SCORE >= 96 THEN "S"
WHEN YG.SCORE >= 90 THEN "A"
WHEN YG.SCORE >= 80 THEN "B"
ELSE "C" END AS GRADE,
CASE 
WHEN YG.SCORE >= 96 THEN (SAL) * 0.2
WHEN YG.SCORE >= 90 THEN (SAL) * 0.15
WHEN YG.SCORE >= 80 THEN (SAL) * 0.1
ELSE SAL * 0 END AS BONUS
FROM HR_EMPLOYEES HE
JOIN YEAR_GRADE YG
ON HE.EMP_NO = YG.EMP_NO
ORDER BY HE.EMP_NO;