WITH STRAIGHT AS (
    SELECT COUNT(RR.MEMBER_ID) AS CNT, RR.MEMBER_ID, MP.MEMBER_NAME
    FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(RR.MEMBER_ID) DESC
)

SELECT ST.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN (
    SELECT *
    FROM STRAIGHT
    WHERE CNT = (SELECT MAX(CNT) FROM STRAIGHT))
    AS ST
ON ST.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;

