WITH MAX_ECO AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX,
    YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
 )
SELECT YEAR, (MAX - ED.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM MAX_ECO ME
JOIN ECOLI_DATA ED
ON ME.YEAR = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;