SELECT DISTINCT(CC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
WHERE DATE_FORMAT(RH.START_DATE, '%Y-%m') = '2022-10'
AND CC.CAR_TYPE = '세단'
ORDER BY CC.CAR_ID DESC;