WITH INFO AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
    HAVING YEAR = 2022
) # 여기서 max ?

SELECT INFO.SCORE, HE.EMP_NO, HE.EMP_NAME,
HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN INFO
ON HE.EMP_NO = INFO.EMP_NO
# JOIN HR_DEPARTMENT HD
# ON HD.DEPT_ID = HE.DEPT_ID
WHERE INFO.SCORE = (
    SELECT MAX(SCORE)
    FROM INFO
)

# 2022년도 평가 점수가 가장 높은 사원