SELECT GB.TITLE, GB.BOARD_ID, GP.REPLY_ID, GP.WRITER_ID, GP.CONTENTS, 
DATE_FORMAT(GP.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_REPLY as GP
JOIN USED_GOODS_BOARD as GB
ON GB.BOARD_ID = GP.BOARD_ID
WHERE DATE_FORMAT(GB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY GP.CREATED_DATE, GB.TITLE;