SELECT COUNT(*) AS FISH_COUNT,
MAX(FI.LENGTH) AS MAX_LENGTH,
FI.FISH_TYPE
FROM (
    SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH, TIME
    FROM FISH_INFO
) AS FI
GROUP BY FI.FISH_TYPE
HAVING AVG(FI.LENGTH) >= 33
ORDER BY FI.FISH_TYPE;