WITH FE_SKILL AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front end'
), 
C_SKILL AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
P_SKILL AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
)

SELECT CASE WHEN SKILL_CODE & P_SKILL.CODE AND SKILL_CODE & FE_SKILL.CODE THEN 'A'
            WHEN SKILL_CODE & C_SKILL.CODE THEN 'B'
            WHEN SKILL_CODE & FE_SKILL.CODE THEN 'C'
            END AS GRADE, ID, EMAIL
FROM DEVELOPERS, P_SKILL, FE_SKILL, C_SKILL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;