SELECT bk.BOOK_ID, au.AUTHOR_NAME, 
DATE_FORMAT(bk.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK bk
JOIN AUTHOR au
ON bk.AUTHOR_ID = au.AUTHOR_ID
WHERE bk.CATEGORY = '경제'
ORDER BY bk.PUBLISHED_DATE